"use client";
import {FormEvent,useState} from "react";
type Status="available"|"taken"|"unknown"|"checking";type Result={platform:string,label:string,status:Status,detail:string,url?:string};
const labels:Record<string,string>={github:"GitHub",youtube:"YouTube",linkedin:"LinkedIn",reddit:"Reddit",threads:"Threads",twitch:"Twitch",pinterest:"Pinterest",snapchat:"Snapchat",bluesky:"Bluesky",mastodon:"Mastodon",telegram:"Telegram",producthunt:"Product Hunt",substack:"Substack",medium:"Medium",devto:"dev.to",npm:"npm",pypi:"PyPI",dockerhub:"Docker Hub"};
const platforms=Object.keys(labels);const tlds=[".com",".ai",".io",".dev",".co"];
const apiUrl=(process.env.NEXT_PUBLIC_CHECK_API_URL||"").replace(/\/$/,"");
async function checkProfile(platform:string,name:string):Promise<Result>{
  if(!apiUrl)return{platform,label:labels[platform],status:"unknown",detail:"Live checker is not configured yet. The CLI is available now."};
  try{const r=await fetch(`${apiUrl}/check?platform=${encodeURIComponent(platform)}&name=${encodeURIComponent(name)}`);if(!r.ok)throw new Error();const data=await r.json();return{...data,label:labels[platform]};}
  catch{return{platform,label:labels[platform],status:"unknown",detail:"Live checker could not be reached. No availability claim was made."}}
}
async function checkDomain(name:string,tld:string):Promise<Result>{const value=`${name}${tld}`,platform=`domain:${tld}`,url=`https://rdap.org/domain/${encodeURIComponent(value)}`;try{const r=await fetch(url);if(r.ok)return{platform,label:value,status:"taken",detail:"RDAP registration found.",url};if(r.status===404)return{platform,label:value,status:"available",detail:"No RDAP record. Confirm with a registrar.",url};return{platform,label:value,status:"unknown",detail:`RDAP returned HTTP ${r.status}.`,url};}catch{return{platform,label:value,status:"unknown",detail:"Registry request was blocked. No availability claim was made.",url}}}
export default function Checker({compact=false}:{compact?:boolean}){const[name,setName]=useState("");const[rows,setRows]=useState<Result[]>([]);const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();const value=name.trim().toLowerCase().replace(/^@/,"").replace(/[^a-z0-9_.@-]/g,"").slice(0,128);if(!value)return;setBusy(true);const pending=[...platforms.map(platform=>({platform,label:labels[platform],status:"checking" as Status,detail:"Checking live public source…"})),...tlds.map(tld=>({platform:`domain:${tld}`,label:value+tld,status:"checking" as Status,detail:"Checking registry…"}))];setRows(pending);const jobs=[...platforms.map(p=>checkProfile(p,value)),...tlds.map(t=>checkDomain(value,t))];await Promise.all(jobs.map(async job=>{const item=await job;setRows(current=>current.map(row=>row.platform===item.platform?item:row))}));setBusy(false)}const counts=rows.reduce((a,r)=>(a[r.status]=(a[r.status]||0)+1,a),{} as Record<Status,number>);return <div className={compact?"checker":"panel"}><form onSubmit={submit}><div className="formlabel"><label htmlFor={compact?"quick-name":"name"}>Check one name everywhere</label>{apiUrl&&<span className="livebadge">Live checks</span>}</div><div className="inputrow"><input id={compact?"quick-name":"name"} value={name} onChange={e=>setName(e.target.value)} placeholder="yourname" autoComplete="off"/><button disabled={busy}>{busy?"Checking…":"Check name"}</button></div><p className="hint">18 platforms plus 5 domains. Blocks and timeouts stay unknown. No fake green lights.</p></form>{rows.length>0&&<>{!compact&&<div className="summary" aria-live="polite"><span><b>{counts.available||0}</b> available</span><span><b>{counts.taken||0}</b> taken</span><span><b>{counts.unknown||0}</b> unknown</span></div>}<div className={compact?"miniresults":"results"}>{rows.map(row=><div className={compact?"minirow":"result"} key={row.platform}><span><i className={`dot ${row.status}`}/>{row.url&&!compact?<a href={row.url} target="_blank" rel="noreferrer">{row.label}</a>:row.label}</span><span className="meta"><span className={`status ${row.status}`}>{row.status}</span>{!compact&&<small className="detail">{row.detail}</small>}</span></div>)}</div></>}</div>}
